filebeat.inputs:
  - type: aws-s3
    enabled: true
    number_of_workers: 4
    bucket_arn: "arn:aws:s3:::aegislenz-s3"
    access_key_id: "${AWS_ACCESS_KEY_ID}"
    secret_access_key: "${AWS_SECRET_ACCESS_KEY}"
    region: "${AWS_REGION}"
    file_selectors:
      - regex: 'AWSLogs/713881791527/CloudTrail/us-east-1/.*\.json.gz'
    expand_event_list_from_field: "Records"
    prefix: "AWSLogs/713881791527/CloudTrail/us-east-1/"
    compression: "gzip"

    start_position: beginning
    scan_frequency: 1m
    close_inactive: 10m
    ignore_older: 0s
    scan.start_time: "2024-11-25T00:00:00Z"

    processors:
      - add_fields:
          target: ""
          fields:
            ingest_time: "{{_ingest.timestamp}}"  
      - drop_fields:
          fields: ["host", "agent", "@version", "input"]

output.logstash:
  hosts: ['logstash:5045']                        

logging.level: debug                        
logging.selectors: ["*"]