filebeat.inputs:
  - type: aws-s3
    enabled: true
    number_of_workers: 3
    bucket_arn: "arn:aws:s3:::aegislenz-s3"
    access_key_id: "${AWS_ACCESS_KEY_ID}"
    secret_access_key: "${AWS_SECRET_ACCESS_KEY}"
    region: "${AWS_REGION}"
    file_selectors:
      - regex: 'AWSLogs/713881791527/CloudTrail/us-east-1/.*\.json.gz'
    expand_event_list_from_field: "Records"
    prefix: "AWSLogs/713881791527/CloudTrail/us-east-1/"
    compression: "gzip"
    start_position: beginning
    scan_frequency: 5m
    close_inactive: 10m

output.logstash:
  hosts: ['logstash:5045']

logging.level: debug
